// create list of product objects, with key-value pairs of String keys and
// dynamic values of string and int
final List<Map<String,dynamic>> productData = [
  {"id":1,
    "productName": "Apple Watch",
    "productImage": "lib/assets/images/watch1.png",
    "description": "Beautiful watch you'll love to have",
    "price": 53000,
  },
  {
    "id":2,
    "productName": "Rolex",
    "productImage": "lib/assets/images/watch2.png",
    "description": "Keeping you updated since 1856.",
    "price": 8000,
  },
  {
    "id":3,
    "productName": "Samsung Watch",
    "productImage": "lib/assets/images/watch3.png",
    "description": "Not just a watch,but a companion",
    "price":  80000,
  },
  {
    "id":4,
    "productName": "Hublot",
    "productImage": "lib/assets/images/watch4.png",
    "description": "The wild beast that survuives all weather.",
    "price":  2000,
  },
  {
    "id":5,
    "productName": "McAffe",
    "productImage": "lib/assets/images/watch5.png",
    "description": "Rose in concrette",
    "price":  1500,
  },
  {
    "id":6,
    "productName": "Blonge",
    "productImage": "lib/assets/images/watch6.png",
    "description": "Esquisitely built for fashion lovers.",
    "price":  9000,
  },
  {
    "id":7,
    "productName": "Oraimo",
    "productImage": "lib/assets/images/watch7.png",
    "description": "Durable long-lasting sports watch",
    "price":  22000,
  },
  {
    "id":8,
    "productName": "Saofine",
    "productImage": "lib/assets/images/watch9.png",
    "description": "Long lasting watch for correct time keeping.",
    "price":  7000,
  },
  {
    "id":9,
    "productName": "Fendi",
    "productImage": "lib/assets/images/watch10.png",
    "description": "luxry watch at its best",
    "price":  2000,
  },
  {
    "id":10,
    "productName": "GucciXL",
    "productImage": "lib/assets/images/watch11.png",
    "description": "Great time piece",
    "price":  6000,
  },
  {
    "id":11,
    "productName": "Samsung Supa1",
    "productImage": "lib/assets/images/watch12.png",
    "description": "State of the art watch",
    "price":  34000,
  },
  {
    "id":12,
    "productName": "Adipro",
    "productImage": "lib/assets/images/watch13.png",
    "description": "Beautiful watch",
    "price":  7000,
  },
  {
    "id":13,
    "productName": "Apple w2",
    "productImage": "lib/assets/images/watch8.png",
    "description": "Gets all your vitals in check and more",
    "price":  18000,
  }
];
